import project1Image from '@assets/images/project-1.png';

export const projectsData = [
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
  {
    demoLink: '',
    codeLink: '',
    imgSrc: project1Image,
    imgAlt: '',
    title: '',
    desc: '',
    tagsList: ['HTML', 'CSS', 'JS'],
  },
];
